name:                subfix
version:             0.1.0
license:             GPL-3
author:              "Jonathan Lamothe"
maintainer:          "jonathan@jlamothe.net"
copyright:           "Jonathan Lamothe"
homepage:            "https://git.fingerprintsoftware.ca/jlamothe/subfix"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Fixes .srt files
category:            Utilities

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jlamothe/subfix#readme>

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - transformers >=0.5.6.2 && <0.6

executables:
  subfix:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - subfix

tests:
  subfix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - subfix
    - hspec >=2.7.4 && <2.8
